# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/cft-dm', '-f', 'Dockerfile', '.']

# Simple sanity check: invoke the new cft-dm container to confirm that it was
# built correctly.
- name: 'gcr.io/$PROJECT_ID/cft-dm'
  args: ['--version']

images:
- 'gcr.io/$PROJECT_ID/cft-dm'

timeout: 1200s
