# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build the Bazel builder and output the version we built with.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bazel', '.']
- name: 'gcr.io/$PROJECT_ID/bazel'
  args: ['version']

# Build the example.
- name: 'gcr.io/$PROJECT_ID/bazel'
  args: ['run', '--spawn_strategy=standalone', '//:target', '--verbose_failures']
  dir: 'examples'
- name: 'gcr.io/$PROJECT_ID/bazel'
  args: ['run', '--spawn_strategy=standalone', '//:checkargs', '--verbose_failures', '--', 'a', 'b', 'c']
  dir: 'examples'
- name: 'gcr.io/$PROJECT_ID/bazel'
  entrypoint: '/bin/bash'
  args: ['invocation_id_test.sh']

# Example was built as bazel:target.
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'bazel:target']

# TODO(mattmoor): Test docker_push as well.

images: ['gcr.io/$PROJECT_ID/bazel']
