# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BAZEL_VERSION=8.1.1'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:latest'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1.1'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BAZEL_VERSION=7.4.1'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4.1'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4'
  - '--tag=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7'
  - '.'

# Print for each version
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:latest'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1.1'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4.1'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4'
  args: ['version']
- name: '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7'
  args: ['version']

images:
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:latest'
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1.1'
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8.1'  
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:8'
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4.1'
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7.4'  
 - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/bazel:7'

timeout: 2400s

substitutions:
  _REGION: "us-central1"