# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build the Bazel builder and output the version we built with.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/bazel', '.']
- name: 'gcr.io/$PROJECT_ID/bazel'
  args: ['version']

# Build the example.
- name: 'gcr.io/$PROJECT_ID/bazel'
  args: ['run', '--spawn_strategy=standalone', '//:target', '--verbose_failures']
  dir: 'examples'

# Example was built as bazel:target.
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'bazel:target']

images: ['gcr.io/$PROJECT_ID/bazel']
