# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml
#

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=6.14.1'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-6.14.1'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.11.1'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-8.11.1'
  # 8.11.1 is tagged :latest
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=9.11.1'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-9.11.1'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.0.0'
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.0.0'
  # 10.0.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/yarn-puppeteer:current'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-6.14.1'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-8.11.1'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-9.11.1'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.0.0'
  args: ['--version']

# Test the examples with :latest

# hello_world
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:latest'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:current'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-6.14.1'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-8.11.1'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-9.11.1'
- 'gcr.io/$PROJECT_ID/yarn-puppeteer:node-10.0.0'
- 'gcr.io/$PROJECT_ID/nodejs/yarn-puppeteer'
