steps:
# Run tests.
- name: 'golang:stretch'
  entrypoint: 'go'
  args: ['test', './...']

# Build the gke-deploy binary and put into the builder image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gke-deploy', '.']
- name: 'gcr.io/$PROJECT_ID/gke-deploy'
  args: ['--help']

images:
- 'gcr.io/$PROJECT_ID/gke-deploy'

