# Example build script to create a Docker image from a .NET Core 2.0 Web Api app.
steps:

# .NET Core 2.0 by default restores before any build, so we can
# combine the restore and publish operations in a single statement.
- name: 'microsoft/dotnet:sdk'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]

# Build the app image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/testapp:2.1', '.' ]
  dir: './bin/Release/netcoreapp2.1/publish'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/testapp:2.1' ]
