# Example build script to create a Docker image from a .NET Core 1.1 Web Api app.
steps:

# Use a persistent volume to store the packages for this app and have them
# available across calls to the 'dotnet' builder.
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'restore', '--packages', '/packages' ]
  volumes:
  - name: 'packages'
    path: '/packages'
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  volumes:
  - name: 'packages'
    path: '/packages'

# Build the apps image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/testapp', '.' ]
  dir: './bin/Release/netcoreapp1.1/publish'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/testapp' ]
