steps:
- name: 'gcr.io/cloud-builders/golang-project'
  args:
  - 'product/server'
  - 'product/subtool'
  - 'product/subtool/subpkg'
  - '--entrypoint=server'
  - '--tag=gcr.io/$PROJECT_ID/golang_project_multi_bin'
  env: ['PROJECT_ROOT=product']
images: ['gcr.io/$PROJECT_ID/golang_project_multi_bin']
