load("@bazel_tools//tools/build_defs/docker:docker.bzl", "docker_pull")

docker_pull(
    name = "wheezy",
    repository = "debian",
    digest = "sha256:d3892ebd85bb21b161e9d170beefd6c444d9bd58aba3998e1f67aa842fbedb9d",
)
