apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test-daemon-set
spec:
  template:
    metadata:
      labels:
        app: test-daemon-set
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app
