apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-daemonset","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"test-app"}},"template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app"}]}}}}
  creationTimestamp: 2019-06-10T19:43:42Z
  generation: 1
  labels:
    app: test-app
  name: test-app-daemonset
  namespace: default
  resourceVersion: "5214160"
  selfLink: /apis/apps/v1/namespaces/default/daemonsets/test-app-daemonset
  uid: 0d6d67fb-8bb8-11e9-8840-42010a8e00dc
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: Always
        name: test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
  observedGeneration: 1
