apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-deployment","namespace":"test-local-deploy-all"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"test-app"}},"template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app"}]}}}}
  creationTimestamp: 2019-06-11T14:46:46Z
  generation: 2
  labels:
    app: test-app
  name: test-app-deployment
  namespace: test-local-deploy-all
  resourceVersion: "6031223"
  selfLink: /apis/extensions/v1beta1/namespaces/test-local-deploy-all/deployments/test-app-deployment
  uid: bc45e2fe-8c57-11e9-8840-42010a8e00dc
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: IfNotPresent
        name: test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-06-11T14:46:46Z
    lastUpdateTime: 2019-06-11T14:46:46Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
