apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: OVERRIDDEN
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: OVERRIDDEN
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app
