apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-app-hpa
  namespace: default
  labels:
    app: test-app
spec:
  scaleTargetRef:
    kind: Deployment
    name: test-app
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
