apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: REPLACED
    name: test-app-1
  - image: REPLACED
    name: test-app-2
  - image: gcr.io/cbd-test/do-not-update:latest
    name: do-not-update
