apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ReplicationController","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-replicationcontroller","namespace":"test-local-deploy-all"},"spec":{"replicas":2,"selector":{"app":"test-app"},"template":{"metadata":{"labels":{"app":"test-app"},"name":"test-app"},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: 2019-06-11T15:29:16Z
  generation: 2
  labels:
    app: test-app
  name: test-app-replicationcontroller
  namespace: test-local-deploy-all
  resourceVersion: "6040056"
  selfLink: /api/v1/namespaces/test-local-deploy-all/replicationcontrollers/test-app-replicationcontroller
  uid: ac5b7d26-8c5d-11e9-8840-42010a8e00dc
spec:
  replicas: 2
  selector:
    app: test-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
      name: test-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 2
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
