apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"test-app-rs"},"name":"test-app-replicaset","namespace":"test-local-deploy-all"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"test-app-rs"}},"template":{"metadata":{"labels":{"app":"test-app-rs"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app"}]}}}}
  creationTimestamp: 2019-06-11T14:46:46Z
  generation: 1
  labels:
    app: test-app-rs
  name: test-app-replicaset
  namespace: test-local-deploy-all
  resourceVersion: "6031925"
  selfLink: /apis/apps/v1/namespaces/test-local-deploy-all/replicasets/test-app-replicaset
  uid: bc76c7a7-8c57-11e9-8840-42010a8e00dc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app-rs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app-rs
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: IfNotPresent
        name: test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
