apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-replicaset","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"test-app"}},"template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app"}]}}}}
  creationTimestamp: 2019-06-10T16:47:52Z
  generation: 2
  labels:
    app: test-app-rs
  name: test-app-replicaset
  namespace: default
  resourceVersion: "5181211"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/test-app-replicaset
  uid: 7cd02917-8b9f-11e9-8840-42010a8e00dc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-rs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app-rs
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: Always
        name: test-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  fullyLabeledReplicas: 2
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
