apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    foo: bar
  name: test-replication-controller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: test-replication-controller
        foo: bar
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app
