apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"a":"b","app":"test-app","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"test-app","app.kubernetes.io/version":"deploy","c":"d"},"name":"test-app","namespace":"foobar"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"test-app"},"type":"NodePort"}}
  creationTimestamp: 2019-06-07T16:19:01Z
  labels:
    a: b
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: test-app
    app.kubernetes.io/version: test
    c: d
  name: test-app
  namespace: foobar
  resourceVersion: "4472473"
  selfLink: /api/v1/namespaces/foobar/services/test-app
  uid: f5cea3f6-893f-11e9-8840-42010a8e00dc
spec:
  clusterIP: 10.31.252.53
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31565
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
