apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  annotations:
    foo: bar
  name: test-stateful-set
spec:
  replicas: 3
  serviceName: test-stateful-set
  template:
    metadata:
      annotations:
        foo: bar
      labels:
        app: test-stateful-set
    spec:
      containers:
        - image: gcr.io/cbd-test/test-app:latest
          name: test-app
          terminateGracePeriodSeconds: 10
