apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-statefulset","namespace":"test-local-deploy-all"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"test-app"}},"serviceName":"test-app-statefulset-service","template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app","ports":[{"containerPort":80,"name":"web"}]}]}}}}
  creationTimestamp: 2019-06-11T14:46:46Z
  generation: 2
  labels:
    app: test-app
  name: test-app-statefulset
  namespace: test-local-deploy-all
  resourceVersion: "6032068"
  selfLink: /apis/apps/v1/namespaces/test-local-deploy-all/statefulsets/test-app-statefulset
  uid: bcbb0631-8c57-11e9-8840-42010a8e00dc
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  serviceName: test-app-statefulset-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        imagePullPolicy: IfNotPresent
        name: test-app
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: test-app-statefulset-7895c5b9fb
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updateRevision: test-app-statefulset-7895c5b9fb
  updatedReplicas: 1
