apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"test-app"},"name":"test-app-statefulset","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"test-app"}},"serviceName":"test-app-statefulset-service","template":{"metadata":{"labels":{"app":"test-app"}},"spec":{"containers":[{"image":"gcr.io/cbd-test/test-app:latest","name":"test-app","ports":[{"containerPort":80,"name":"web"}]}]}}}}
  creationTimestamp: 2019-06-10T19:58:14Z
  generation: 1
  labels:
    app: test-app
  name: test-app-statefulset
  namespace: default
  resourceVersion: "5216586"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/test-app-statefulset
  uid: 1517d0e3-8bba-11e9-8840-42010a8e00dc
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-app
  serviceName: test-app-statefulset-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
        - image: gcr.io/cbd-test/test-app:latest
          imagePullPolicy: Always
          name: test-app
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  observedGeneration: 1
  replicas: 0
