# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build old tagged images.
# TODO(jasonhall): Deprecate and stop building these tagged images. Users
# should use the official gradle image directly.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=GRADLE_VERSION=4.6-jdk8'
  - '--tag=gcr.io/$PROJECT_ID/gradle:4.6-jdk-8'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=GRADLE_VERSION=4.0-jdk8'
  - '--tag=gcr.io/$PROJECT_ID/gradle:4.0-jdk-8'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=GRADLE_VERSION=3.5-jdk8'
  - '--tag=gcr.io/$PROJECT_ID/gradle:3.5-jdk-8'
  - '.'

# Build the latest version.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/gradle'
  - '.'

# Run examples
- name: 'gcr.io/$PROJECT_ID/gradle:4.6-jdk-8'
  args: ['build']
  dir: 'examples/spring_boot'
- name: 'gcr.io/$PROJECT_ID/gradle:4.0-jdk-8'
  args: ['build']
  dir: 'examples/spring_boot'
- name: 'gcr.io/$PROJECT_ID/gradle:3.5-jdk-8'
  args: ['build']
  dir: 'examples/spring_boot'

# TODO(jasonhall): The spring boot example is not compatible with gradle 5.2
#- name: 'gcr.io/$PROJECT_ID/gradle'
#  args: ['build']
#  dir: 'examples/spring_boot'

# Demonstrate using the gradle image directly.
# TODO(jasonhall): This doesn't work because it doesn't have USER root
# See https://github.com/keeganwitt/docker-gradle/issues/29
#- name: 'gradle:4.6-jdk11-slim'
#  args: ['gradle', 'build']
#  dir: 'examples/spring_boot'

images:
- 'gcr.io/$PROJECT_ID/gradle'
- 'gcr.io/$PROJECT_ID/gradle:4.6-jdk-8'
- 'gcr.io/$PROJECT_ID/gradle:4.0-jdk-8'
- 'gcr.io/$PROJECT_ID/gradle:3.5-jdk-8'
