# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--pull', '--tag=gcr.io/$PROJECT_ID/gsutil', '.']
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['version']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['ls']

images: ['gcr.io/$PROJECT_ID/gsutil']
