# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--pull'
  - '--tag=gcr.io/$PROJECT_ID/gsutil'
  - '.'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['-v']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['storage', 'ls']

images:
- 'gcr.io/$PROJECT_ID/gsutil'
