FROM launcher.gcr.io/google/ubuntu16_04

ENV CRED_HELPER_VERSION=1.4.1

RUN  curl -L https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${CRED_HELPER_VERSION}/docker-credential-gcr_linux_amd64-${CRED_HELPER_VERSION}.tar.gz  | \
       tar xz -O docker-credential-gcr > /usr/local/bin/docker-credential-gcr && \
     chmod +x /usr/local/bin/docker-credential-gcr

RUN docker-credential-gcr configure-docker
