FROM ubuntu:trusty

# Based on instructions from:
# https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#uninstall-old-versions
RUN \
   apt-get -y update && \
   apt-get install -y \
      linux-image-extra-$(uname -r) \
      linux-image-extra-virtual \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common && \
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
   add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable edge" && \
   apt-get -y update

ARG DOCKER_VERSION=17.06.1~ce-0~ubuntu
RUN apt-get install -y docker-ce=${DOCKER_VERSION} unzip

ENTRYPOINT ["/usr/bin/docker"]
