FROM us-docker.pkg.dev/cloud-builders-dev/cloud-builders/docker-base
LABEL org.opencontainers.image.source="https://github.com/GoogleCloudPlatform/cloud-builders" \
      org.opencontainers.image.vendor="Google LLC"

ARG DOCKER_VERSION=VERSION

RUN apt-get -y install \
        docker-ce=${DOCKER_VERSION} \
        docker-ce-cli=${DOCKER_VERSION} \
        docker-compose docker-compose-plugin && \
    apt-get clean

ENTRYPOINT ["/usr/bin/docker"]
