# Cloud builder for the dotnet builder.
#
# TODO(franklinn): Stop tagging csharp/dotnet images once usage has dropped off.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/dotnet'
  - '--tag=gcr.io/$PROJECT_ID/csharp/dotnet'
  - '.'

# Verify the version output of the supported SDKs.
- name: 'gcr.io/$PROJECT_ID/dotnet'
  entrypoint: 'bash'
  args: ['-c', '[[ $(dotnet --version) == "1.0.0-preview2-003156" ]]']
  dir: 'configs/config-1.0.0'
- name: 'gcr.io/$PROJECT_ID/dotnet'
  entrypoint: 'bash'
  args: ['-c', '[[ $(dotnet --version) == "1.1.5" ]]']
  dir: 'configs/config-1.1.5'
- name: 'gcr.io/$PROJECT_ID/dotnet'
  entrypoint: 'bash'
  args: ['-c', '[[ $(dotnet --version) == "2.1.3" ]]']
  dir: 'configs/config-2.1.3'

images:
- 'gcr.io/$PROJECT_ID/dotnet'
- 'gcr.io/$PROJECT_ID/csharp/dotnet'
