FROM  mcr.microsoft.com/dotnet/core/sdk:2.1
LABEL org.opencontainers.image.source="https://github.com/GoogleCloudPlatform/cloud-builders" \
      org.opencontainers.image.vendor="Google LLC"

ENTRYPOINT ["dotnet"]
