steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build", "-t", "$_IMAGE_NAME:$_IMAGE_VERSION", ".", "-f", "$_DOCKERFILE_PATH"]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "$_IMAGE_NAME:$_IMAGE_VERSION"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: 'Deploy'
  args:
  - 'run'
  - '--image=$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--expose=80'
  - '--app=$_K8S_APP_NAME'
  - '--version=$_IMAGE_VERSION'
  - '--namespace=$_K8S_NAMESPACE'
  - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
  - '--cluster=$_GKE_CLUSTER'
  - '--location=$_GKE_LOCATION'
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'Save suggested base configs to bucket'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET/$BUILD_ID/suggested
    echo "Copied suggested base configs to gs://$_OUTPUT_BUCKET/$BUILD_ID/suggested"
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'
artifacts:
  objects:
    location: 'gs://$_OUTPUT_BUCKET/$BUILD_ID/expanded'
    paths: ['output/expanded/*']
substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _IMAGE_NAME:
  _IMAGE_VERSION:
  _GKE_CLUSTER:
  _GKE_LOCATION:
  _K8S_APP_NAME:
  _K8S_NAMESPACE:
  _K8S_LABELS:
  _OUTPUT_BUCKET:
options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['gcp-cloud-build-deploy', '$_K8S_APP_NAME']
