steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/kubectl'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/kubectl'
  - '.'

images: 
- 'gcr.io/$PROJECT_ID/kubectl'
# Regional AR Mirrors
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/kubectl'
# GCR to AR Migration
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/kubectl'
