# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
# Build the alpine and debian versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.alpine'
  - '--tag=gcr.io/$PROJECT_ID/go'
  - '--tag=gcr.io/$PROJECT_ID/go:1.15'
  - '--tag=gcr.io/$PROJECT_ID/go:alpine'
  - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.15'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.15'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.15'

  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.debian'
  - '--tag=gcr.io/$PROJECT_ID/go:debian'
  - '--tag=gcr.io/$PROJECT_ID/go:debian-1.15'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.15'

  - '.'

# Ensure that "go get" works
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['get', 'golang.org/x/net/context']
  env: ['GOPATH=/tmp']

# Test the examples.

- name: 'golang'
  args: ['go', 'build', '.']
  dir: 'examples/module'
- name: 'busybox'
  args: ['./module']
  dir: 'examples/module'

# examples/hello_world
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['test', 'hello']
  env: ['PROJECT_ROOT=hello']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=hello']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

# examples/whole_workspace
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['test', 'hello']
  env: ['GOPATH=.']
  dir: 'examples/whole_workspace'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['install', 'hello']
  env: ['GOPATH=.']
  dir: 'examples/whole_workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/whole_workspace'

# examples/whole_workspace with an absolute path
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['test', 'hello']
  env: ['GOPATH=/workspace/examples/whole_workspace']
  dir: 'examples/whole_workspace'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['install', 'hello']
  env: ['GOPATH=/workspace/examples/whole_workspace']
  dir: 'examples/whole_workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/whole_workspace'

# examples/import_workspace
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['test', 'hello']
  dir: 'examples/import_workspace'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['build', 'hello']
  dir: 'examples/import_workspace'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['install', 'hello']
  dir: 'examples/import_workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/import_workspace'

# examples/nested_workspace
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['test', 'hello']
  env: ['GOPATH=subproject']
  dir: 'examples/nested_workspace'
- name: 'gcr.io/$PROJECT_ID/go'
  args: ['install', 'hello']
  env: ['GOPATH=subproject']
  dir: 'examples/nested_workspace'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/nested_workspace'

# examples/https_test
# with alpine/default
- name: 'gcr.io/$PROJECT_ID/go:alpine'
  args: ['install', 'https_test']
  dir: 'examples/https_test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.alpine', '--tag=https_test:alpine', '.']
  dir: 'examples/https_test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'https_test:alpine']
# clear out the alpine binary.
- name: 'alpine'
  args: ['rm', 'gopath/bin/https_test']
  dir: 'examples/https_test'
# with debian
- name: 'gcr.io/$PROJECT_ID/go:debian'
  args: ['install', 'https_test']
  dir: 'examples/https_test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.ubuntu', '--tag=https_test:ubuntu', '.']
  dir: 'examples/https_test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'https_test:ubuntu']

# Go 1.16
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.alpine'
  - '--build-arg=VERSION=1.16'
  - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.16'
  - '--tag=gcr.io/$PROJECT_ID/go:1.16'
  # Regional AR Mirrors
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.16'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.16'

  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.debian'
  - '--build-arg=VERSION=1.16'
  - '--tag=gcr.io/$PROJECT_ID/go:debian-1.16'
  # Regional AR Mirrors
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.16'

  - '.'

# Go 1.17
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.alpine'
  - '--build-arg=VERSION=1.17'
  - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.17'
  - '--tag=gcr.io/$PROJECT_ID/go:1.17'
  # Regional AR Mirrors
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.17'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.17'

  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.debian'
  - '--build-arg=VERSION=1.17'
  - '--tag=gcr.io/$PROJECT_ID/go:debian-1.17'
  # Regional AR Mirrors
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.17'

  - '.'

# Go 1.18
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.alpine'
  - '--build-arg=VERSION=1.18'
  - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.18'
  - '--tag=gcr.io/$PROJECT_ID/go:1.18'
  # Regional AR Mirrors
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.18'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.18'

  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.debian'
  - '--build-arg=VERSION=1.18'
  - '--tag=gcr.io/$PROJECT_ID/go:debian-1.18'
  # Regional AR Mirrors
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
  # GCR to AR Migration
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.18'

  - '.'

  # Go 1.19
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-f'
    - 'Dockerfile.alpine'
    - '--build-arg=VERSION=1.19'
    - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.19'
    - '--tag=gcr.io/$PROJECT_ID/go:1.19'
    # Regional AR Mirrors
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
    # GCR to AR Migration
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.19'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.19'

    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-f'
    - 'Dockerfile.debian'
    - '--build-arg=VERSION=1.19'
    - '--tag=gcr.io/$PROJECT_ID/go:debian-1.19'
    # Regional AR Mirrors
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
    # GCR to AR Migration
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.19'

    - '.'

  # Go 1.20
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-f'
    - 'Dockerfile.alpine'
    - '--build-arg=VERSION=1.20'
    - '--tag=gcr.io/$PROJECT_ID/go:alpine-1.20'
    - '--tag=gcr.io/$PROJECT_ID/go:1.20'
    # Regional AR Mirrors
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
    # GCR to AR Migration
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.20'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.20'

    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-f'
    - 'Dockerfile.debian'
    - '--build-arg=VERSION=1.20'
    - '--tag=gcr.io/$PROJECT_ID/go:debian-1.20'
    # Regional AR Mirrors
    - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'
    - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'
    # GCR to AR Migration
    - '--tag=us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.20'

    - '.'

options:
  env: ['GO111MODULE=auto']
images:
- 'gcr.io/$PROJECT_ID/go'
- 'gcr.io/$PROJECT_ID/go:alpine'
- 'gcr.io/$PROJECT_ID/go:debian'
- 'gcr.io/$PROJECT_ID/go:1.15'
- 'gcr.io/$PROJECT_ID/go:1.16'
- 'gcr.io/$PROJECT_ID/go:1.17'
- 'gcr.io/$PROJECT_ID/go:1.18'
- 'gcr.io/$PROJECT_ID/go:1.19'
- 'gcr.io/$PROJECT_ID/go:1.20'
- 'gcr.io/$PROJECT_ID/go:alpine-1.15'
- 'gcr.io/$PROJECT_ID/go:debian-1.15'
- 'gcr.io/$PROJECT_ID/go:alpine-1.16'
- 'gcr.io/$PROJECT_ID/go:debian-1.16'
- 'gcr.io/$PROJECT_ID/go:alpine-1.17'
- 'gcr.io/$PROJECT_ID/go:debian-1.17'
- 'gcr.io/$PROJECT_ID/go:alpine-1.18'
- 'gcr.io/$PROJECT_ID/go:debian-1.18'
- 'gcr.io/$PROJECT_ID/go:alpine-1.19'
- 'gcr.io/$PROJECT_ID/go:debian-1.19'
- 'gcr.io/$PROJECT_ID/go:alpine-1.20'
- 'gcr.io/$PROJECT_ID/go:debian-1.20'

# Regional AR Mirrors (US)
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'

# Regional AR Mirrors (ASIA)
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'

# Regional AR Mirrors (EUROPE)
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.15'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.16'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.17'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.18'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.19'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:1.20'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.15'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.15'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.16'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.16'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.17'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.17'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.18'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.18'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.19'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.19'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:alpine-1.20'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/go:debian-1.20'

# GCR to AR Migration
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:1.20'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.15'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.16'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.17'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.18'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.19'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:alpine-1.20'
- 'us-docker.pkg.dev/$PROJECT_ID/gcr.io/go:debian-1.20'

timeout: 2400s
