# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml
#
# TODO(franklinn): Stop tagging nodejs/yarn images once usage has dropped off.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/yarn'
  # Update this tag when you update the yarn version of this build tool
  - '--tag=gcr.io/$PROJECT_ID/yarn:1.3.2'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/yarn'
  - '.'

# Print yarn version.
- name: 'gcr.io/$PROJECT_ID/yarn'
  args: ['--version']

# Test the examples.

# hello_world
- name: 'gcr.io/$PROJECT_ID/yarn'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/yarn'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/yarn'
- 'gcr.io/$PROJECT_ID/yarn:1.3.2'
- 'gcr.io/$PROJECT_ID/nodejs/yarn'
