ARG NODE_VERSION=latest
FROM us-docker.pkg.dev/artifact-foundry-prod/docker-3p-trusted/node@${NODE_VERSION}
LABEL org.opencontainers.image.source="https://github.com/GoogleCloudPlatform/cloud-builders" \
      org.opencontainers.image.vendor="Google LLC"

ENTRYPOINT ["yarn"]
