# Example build script to create a Docker image from a .NET Core 2.0 Web Api app.
steps:

# Use a persistent volume to store the restored packages for this app. The
# packages will available in between calls to the 'dotnet' builder
- name: 'gcr.io/cloud-builders/csharp/dotnet'
  args: [ 'restore', '--packages', '/packages' ]
  volumes:
  - name: 'packages'
    path: '/packages'
- name: 'gcr.io/cloud-builders/csharp/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  volumes:
  - name: 'packages'
    path: '/packages'

# Build the apps image.
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/testapp:2.0', '.' ]
  dir: './bin/Release/netcoreapp2.0/publish'

# Publish the app.
images: [ 'gcr.io/$PROJECT_ID/testapp:2.0' ]
