# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--file=Dockerfile.8-jdk-alpine', '--build-arg=MAVEN_VERSION=3.5.0', '--tag=gcr.io/$PROJECT_ID/java/mvn:3.5.0-jdk-8', '.']

images: ['gcr.io/$PROJECT_ID/java/mvn:3.5.0-jdk-8']
