# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=6.14.4'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-6.14.4'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.12.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.12.0'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.4.0'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=9.11.2'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-9.11.2'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=10.10.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-10.10.0'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=12.18.3'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-12.18.3'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
  # 12.18.3 is tagged :lts
  - '--tag=gcr.io/$PROJECT_ID/npm:lts'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/npm'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=14.10.1'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-14.10.1'
  - '--tag=gcr.io/$PROJECT_ID/npm:latest'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  # 14.10.1 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:current'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=16.18.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-16.18.0'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
  # 16.18.0 is tagged :lts
  - '--tag=gcr.io/$PROJECT_ID/npm:lts'
  - '--tag=gcr.io/$PROJECT_ID/nodejs/npm'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=19.0.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-19.0.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:latest'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
  # 19.0.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:current'
  - '--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-6.14.4'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.12.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-9.11.2'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-10.10.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-12.18.3'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/npm:node-14.10.1'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/npm:node-16.18.0'
  args: ['--version']
- name: 'gcr.io/$PROJECT_ID/npm:node-19.0.0'
  args: ['--version']


# Test the examples with :latest
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/npm:lts'
- 'gcr.io/$PROJECT_ID/npm:latest'
- 'gcr.io/$PROJECT_ID/npm:current'
- 'gcr.io/$PROJECT_ID/npm:node-6.14.4'
- 'gcr.io/$PROJECT_ID/npm:node-8.12.0'
- 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
- 'gcr.io/$PROJECT_ID/npm:node-9.11.2'
- 'gcr.io/$PROJECT_ID/npm:node-10.10.0'
- 'gcr.io/$PROJECT_ID/npm:node-12.18.3'
- 'gcr.io/$PROJECT_ID/npm:node-14.10.1'
- 'gcr.io/$PROJECT_ID/npm:node-16.18.0'
- 'gcr.io/$PROJECT_ID/npm:node-19.0.0'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
- 'asia-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
- 'europe-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:lts'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:latest'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:current'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-6.14.4'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.12.0'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-8.4.0'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-9.11.2'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-10.10.0'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-12.18.3'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-14.10.1'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-16.18.0'
- 'us-docker.pkg.dev/$PROJECT_ID/ga/v1/npm:node-19.0.0'
