# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v6.14.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-6.14.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v8.11.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.11.0'
  # 8.11.0 is tagged :latest
  - '--tag=gcr.io/$PROJECT_ID/npm:latest'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.4.0'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v9.10.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-9.10.0'
  # 9.10.0 is tagged :current
  - '--tag=gcr.io/$PROJECT_ID/npm:current'
  - '.'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-6.14.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.11.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
  args: ['version']
- name: 'gcr.io/$PROJECT_ID/npm:node-9.10.0'
  args: ['version']

# Test the examples with :latest
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images:
- 'gcr.io/$PROJECT_ID/npm:latest'
- 'gcr.io/$PROJECT_ID/npm:current'
- 'gcr.io/$PROJECT_ID/npm:node-6.14.0'
- 'gcr.io/$PROJECT_ID/npm:node-8.11.0'
- 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
- 'gcr.io/$PROJECT_ID/npm:node-9.10.0'
