# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
# Build all supported versions.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v6.11.2'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-6.11.2'
  - '.'
  id: 'node-6.11.2'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=NODE_VERSION=v8.4.0'
  - '--tag=gcr.io/$PROJECT_ID/npm:node-8.4.0'
  - '.'
  id: 'node-8.4.0'

# Print for each version
- name: 'gcr.io/$PROJECT_ID/npm:node-6.11.2'
  args: ['version']
  wait_for: ['node-6.11.2']
  id: 'node-6.11.2-version'
- name: 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
  args: ['version']
  wait_for: ['node-8.4.0']
  id: 'node-8.4.0-version'

# Tag LTS as latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/npm:node-6.11.2', 'gcr.io/$PROJECT_ID/npm']
  wait_for: ['node-6.11.2-version']
  id: 'latest'

# Tag current as current
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/npm:node-8.4.0', 'gcr.io/$PROJECT_ID/npm:current']
  wait_for: ['node-8.4.0-version']
  id: 'current'

# Test the examples.
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['install']
  dir: 'examples/hello_world'
  wait_for: ['latest']
  id: 'latest-install'
- name: 'gcr.io/$PROJECT_ID/npm:latest'
  args: ['test']
  dir: 'examples/hello_world'
  wait_for: ['latest-install']
  id: 'latest-test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'
  wait_for: ['latest-test']
  id: 'latest-build'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['install']
  dir: 'examples/hello_world'
  wait_for: ['current']
  id: 'current-install'
- name: 'gcr.io/$PROJECT_ID/npm:current'
  args: ['test']
  dir: 'examples/hello_world'
  wait_for: ['current-install']
  id: 'current-test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'
  wait_for: ['current-test']
  id: 'current-build'

images:
- 'gcr.io/$PROJECT_ID/npm:latest'
- 'gcr.io/$PROJECT_ID/npm:current'
- 'gcr.io/$PROJECT_ID/npm:node-6.11.2'
- 'gcr.io/$PROJECT_ID/npm:node-8.4.0'
