# In this directory, run the following command to build this builder.
# $ gcloud alpha container builds create . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/npm', '.']


# Print npm version.
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['version']

# Test the examples.

# hello_world
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['install']
  dir: 'examples/hello_world'
- name: 'gcr.io/$PROJECT_ID/npm'
  args: ['test']
  dir: 'examples/hello_world'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.']
  dir: 'examples/hello_world'

images: ['gcr.io/$PROJECT_ID/npm']
